# Site settings
title: 'Points. Lines. Polygons.' # Your Title
tagline: 'a blog on geography and random things' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# permalink: /:title/


# Build settings
# # Jekyll 3 now only supports Kramdown for Markdown
# kramdown:
# # Use GitHub flavored markdown, including triple backtick fenced code blocks
#   input: GFM
#   # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
#   syntax_highlighter: rouge
#   syntax_highlighter_opts:
#   # Use existing pygments syntax highlighting css
#   css_class: 'highlight'

markdown: kramdown
highlighter: pygments
baseurl: "" # the subpath of your site, e.g. /blog
